app/ig/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from flask_login import current_user, login_required
from app.ig.forms import PostForm
from app.models import Post, db, User


ig = Blueprint('ig', __name__, template_folder='igtemplates')


@ig.route('/posts/create', methods=["GET","POST"])
@login_required
def createPost():
    form = PostForm()
    if request.method == "POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            post = Post(title, img_url, caption, current_user.id)
            post.save()
            flash('Successfully created post.', 'success')
        else:
            flash('Invalid form. Please fill out the form correctly.', 'danger')
    return render_template('createpost.html', form=form)

@ig.route('/posts')
def getAllPosts():
    if current_user.is_authenticated:
        posts = current_user.get_followed_posts()
    else:
        posts = Post.query.order_by(Post.date_created.desc()).all()
    return render_template('feed.html', posts=posts)


@ig.route('/posts/<int:post_id>')
def getSinglePost(post_id):
    post = Post.query.get(post_id)
    # post = Post.query.filter_by(id=post_id).first()
    return render_template('singlepost.html', post=post)

@ig.route('/posts/update/<int:post_id>', methods=["GET", "POST"])
@login_required
def updatePost(post_id):
    form = PostForm()
    # post = Post.query.get(post_id)
    post = Post.query.filter_by(id=post_id).first()
    if current_user.id != post.user_id:
        flash('You are not allowed to update another user\'s posts.', 'danger')
        return redirect(url_for('ig.getSinglePost', post_id=post_id))
    if request.method=="POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            post.updatePostInfo(title,img_url,caption)
            post.saveUpdates()
            flash('Successfully updated post.', 'success')
            return redirect(url_for('ig.getSinglePost', post_id=post_id))
        else:
            flash('Invalid form. Please fill out the form correctly.', 'danger')
    return render_template('updatepost.html', form=form,  post=post)


@ig.route('/posts/delete/<int:post_id>')
@login_required
def deletePost(post_id):
    post = Post.query.get(post_id)
    if current_user.id != post.user_id:
        flash('You are not allowed to delete another user\'s posts.', 'danger')
        return redirect(url_for('ig.getSinglePost', post_id=post_id))
    post.delete()
    flash('Successfully delete post.', 'success')
    return redirect(url_for('ig.getAllPosts'))


@ig.route('/follow/<int:user_id>')
@login_required
def followUser(user_id):
    user = User.query.get(user_id)
    current_user.follow(user)
    return redirect(url_for('index'))

@ig.route('/unfollow/<int:user_id>')
@login_required
def unfollowUser(user_id):
    user = User.query.get(user_id)
    current_user.unfollow(user)
    return redirect(url_for('index'))





################# API ROUTES #####################
@ig.route('/api/posts')
def getAllPostsAPI():
    args = request.args
    pin = args.get('pin')
    print(pin, type(pin))
    if pin == '1234':

        posts = Post.query.all()

        my_posts = [p.to_dict() for p in posts]
        return {'status': 'ok', 'total_results': len(posts), "posts": my_posts}
    else:
        return {
            'status': 'not ok',
            'code': 'Invalid Pin',
            'message': 'The pin number was incorrect, please try again.'
        }

@ig.route('/api/posts/<int:post_id>')
def getSinglePostsAPI(post_id):
    post = Post.query.get(post_id)
    if post:
        return {
            'status': 'ok',
            'total_results': 1,
            "post": post.to_dict()
            }
    else:
        return {
            'status': 'not ok',
            'message': f"A post with the id : {post_id} does not exist."
        }


@ig.route('/api/posts/create', methods=["POST"])
def createPostAPI():
    data = request.json # this is coming from POST request Body

    title = data['title']
    caption = data['caption']
    user_id = data['user_id']
    img_url = data['img_url']

    post = Post(title, img_url, caption, user_id)
    post.save()

    return {
        'status': 'ok',
        'message': "Post was successfully created."
    }

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    {{ moment.include_moment() }}
    <title>Title</title>
    {% block head %}
    {% endblock %}
</head>
<body>

    {% include 'navbar.html' %}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for c, m in messages %}
                <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                    {{ m }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}


    {% endblock %}
    <div class="foot-wrap">
    <div class="text-center p-3 bg-light footer">
        <a class="text-dark" href="#" style="text-decoration: none;">Finstagram</a>
      </div>
    </div>

</div>
{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
{% endblock %}
</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}

{% block content %}

    This is the contact page!
    <h1>Hi</h1>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

    {% for x in names %}
        
            <div class="card" style="width: 18rem;">
                <!-- <img src="{{ x['img'] }}" class="card-img-top" alt="..."> -->
                <div class="card-body">
                    <h5 class="card-title">{{ x.username }}</h5>
                    {% if current_user.is_authenticated %}
                        {% if current_user.id == x.id %}

                        {% elif x.flag %}
                            <a class="btn btn-danger" href="{{ url_for('ig.unfollowUser', user_id=x.id) }}">Unfollow</a>
                        {% else %}
                            <a class="btn btn-primary" href="{{ url_for('ig.followUser', user_id=x.id) }}">Follow</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
    {% endfor %}


    {{ hello }}

{% endblock %}

app/templates/myteam.html
{% extends 'base.html' %}

{% block content %}


<div class="row">
    {% for p in team %}
        <div class="card" style="width: 18rem;">
            <img src="{{ p.img_url }}" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title">{{ p.name }}</h5>
            <p class="card-text">
                {{ p.ability }}
                <ul>
                    <li>{{ p.hp }}</li>
                    <li>{{ p.attack }}</li>
                    <li>{{ p.defense }}</li>
                </ul>
            </p>
            <a href="/catch/{{ p.name }}" class="btn btn-primary">Catch</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <h5 class="navbar-brand text-dark " href="#"><h5 class="p-3 pt-2">Finstagram</h5></h5>
      <!-- <img src="{{ url_for('static', filename='bike_shop.webp') }}" alt="Logo"> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active text-dark" aria-current="page" href="{{ url_for('ig.getAllPosts') }}">Feed</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="/contact">Contact</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item text-dark" href="/shop">Shop</a></li>
                <li><a class="dropdown-item text-dark" href="/cart">Cart</a></li>
            </ul>

          {% if current_user.is_authenticated %}
            <li class="nav-item text-dark"><a class="nav-link text-dark" href="/posts/create">Create Post</a></li>
          {% else %}

          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              {% if current_user.is_authenticated %}
                <li><a class="dropdown-item text-dark" href="/logout">Log Out</a></li>
              {% else %}
                <li><a class="dropdown-item text-dark" href="/login">Log In</a></li>
                <li><a class="dropdown-item text-dark" href="/signup">Sign Up</a></li>
              {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            {% if current_user.is_authenticated %}
            <p class="nav-link active text-dark" >Hello, {{ current_user.username }}</p>
            {% else %}
            <p class="nav-link active text-dark" >Hello, Guest</p>
            {% endif %}
          </li>
        </ul>
        {% if current_user.is_authenticated %}
        <a href="/cart" class="nav-item mr-2"><i class="fa-solid fa-bag-shopping fa-2x" style="color:black;"></i></a>
        {% endif %}
      </div>
    </div>
  </nav>


  <script src="https://kit.fontawesome.com/57d3ebd9af.js" crossorigin="anonymous"></script>

app/templates/search.html
{% extends 'base.html' %}

{% block content %}

   <form method="POST">
    {{ form.hidden_tag() }}

    {{ form.pokemon_name(class='form-control', placeholder='Enter a Pokemon Name', autocomplete='off') }}
    {{ form.submit(class='btn btn-primary') }}
   </form>
   {% if pokemon_dict %}
    <div class="card" style="width: 18rem;">
        <img src="{{ pokemon_dict.img_url }}" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{ pokemon_dict.name }}</h5>
        <p class="card-text">
            {{ pokemon_dict.ability }}
            <ul>
                <li>{{ pokemon_dict.hp }}</li>
                <li>{{ pokemon_dict.attack }}</li>
                <li>{{ pokemon_dict.defense }}</li>
            </ul>
        </p>
        {% if is_caught %}
        <a href="/release/{{ pokemon_dict.name }}" class="btn btn-danger">Release</a>
        {% else %}
        <a href="/catch/{{ pokemon_dict.name }}" class="btn btn-primary">Catch</a>
        {% endif %}
        </div>
    </div>
   {% endif %}
{% endblock %}